import type { Transaction } from './transactions';

export const initialTransactions: Transaction[] = [
        { id: 1, type: 'Bank-to-Bill', name: 'AWS Cloud Compute', icon: 'ri-amazon-line', amount: '-$1,240.50', evidence: 'INV-2026-10', mappedTo: 'Software Subscriptions', confidence: 98, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 08, 2026' },
        { id: 2, type: 'Card Recon', name: 'Delta Airlines', icon: 'ri-flight-takeoff-line', amount: '-$450.00', evidence: 'Missing Receipt', mappedTo: 'Travel & Entertainment', confidence: 95, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 07, 2026' },
        { id: 3, type: 'Accrual', name: 'Q3 Legal Retainer', icon: 'ri-scales-3-line', amount: 'Est. $5,000.00', evidence: 'Contract #892', mappedTo: 'Legal Expenses', confidence: 92, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 06, 2026' },
        { id: 4, type: 'Bank-to-Bill', name: 'SQ*LCL Coffee Shop', icon: 'ri-restaurant-line', amount: '-$42.00', evidence: 'No matching bill', mappedTo: 'Needs mapping', confidence: 45, status: 'Exception', isException: true, selected: false, date: 'Oct 05, 2026', explanation: "Fuzzy vendor name match failed. 'SQ*LCL' does not match any known vendors. Similar past amounts were coded to Meals & Entertainment." },
        { id: 5, type: 'Bank-to-Bill', name: 'Stripe Payout', icon: 'ri-bank-card-line', amount: '+$8,450.00', evidence: 'Multiple Invoices', mappedTo: 'Needs mapping', confidence: 60, status: 'Exception', isException: true, selected: false, date: 'Oct 05, 2026', explanation: "Batched payment detected. Amount matches sum of INV-101 and INV-102 minus a 2.9% fee, but requires human verification." },
        { id: 6, type: 'Card Recon', name: 'Uber Rides', icon: 'ri-car-line', amount: '-$24.50', evidence: 'Receipt Match', mappedTo: 'Travel & Entertainment', confidence: 99, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 04, 2026' },
        { id: 7, type: 'Bank-to-Bill', name: 'Google Workspace', icon: 'ri-google-fill', amount: '-$120.00', evidence: 'INV-4412', mappedTo: 'Software Subscriptions', confidence: 99, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 03, 2026' },
        { id: 8, type: 'Accrual', name: 'Annual Software License', icon: 'ri-shield-keyhole-line', amount: 'Est. $12,000.00', evidence: 'PO-2026-99', mappedTo: 'Prepaid Expenses', confidence: 96, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 02, 2026' },
        { id: 9, type: 'Card Recon', name: 'WeWork Office Space', icon: 'ri-building-line', amount: '-$2,400.00', evidence: 'Invoice/Receipt Match', mappedTo: 'Rent & Leases', confidence: 97, status: 'Ready to Approve', isException: false, selected: false, date: 'Oct 01, 2026' },
        { id: 10, type: 'Bank-to-Bill', name: 'Unknown Wire Transfer', icon: 'ri-exchange-dollar-line', amount: '+$500.00', evidence: 'Missing Information', mappedTo: 'Suspense Account', confidence: 30, status: 'Exception', isException: true, selected: false, date: 'Sep 30, 2026', explanation: "Inbound wire transfer with no reference text. Could not match against any open Accounts Receivable invoices." },
        { id: 11, type: 'Card Recon', name: 'Slack Technologies', icon: 'ri-slack-line', amount: '-$850.00', evidence: 'Receipt Match', mappedTo: 'Software Subscriptions', confidence: 98, status: 'Ready to Approve', isException: false, selected: false, date: 'Sep 29, 2026' },
        { id: 12, type: 'Accrual', name: 'Marketing Agency Fees', icon: 'ri-megaphone-line', amount: 'Est. $8,500.00', evidence: 'SOW-99', mappedTo: 'Marketing Expenses', confidence: 88, status: 'Ready to Approve', isException: false, selected: false, date: 'Sep 28, 2026' },
    ];
